{% set name = "libspiro" %}
{% set version = "20221101" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fontforge/libspiro/releases/download/{{ version }}/libspiro-dist-{{ version }}.tar.gz
  sha256: 5984fb5af3e4e1f927f3a74850b705a711fb86284802a5e6170b09786440e8be

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libspiro.so  # [unix]

about:
  home: https://github.com/fontforge/libspiro
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: Spiro is the creation of Raph Levien. It simplifies the drawing of beautiful curves.

extra:
  recipe-maintainers:
    - izahn
