{% set name = "libspiro" %}
{% set version = "20220722" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fontforge/libspiro/releases/download/{{ version }}/libspiro-dist-{{ version }}.tar.gz
  sha256: 3b8e54473f3d4d99c014f2630e62f966f5f4e25c28ca59b63d30bd8e9b7593f5

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libspiro.so  # [unix]

about:
  home: https://github.com/fontforge/libspiro
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: Spiro is the creation of Raph Levien. It simplifies the drawing of beautiful curves.

extra:
  recipe-maintainers:
    - izahn
